### ISSUE TITLE
CSRF Verification Error

### ISSUE THREAD

**Issue by antonio-eggberg** [flashingpumpkin/django-socialregistration#1]
Using django-trunk I get the following error just for twitter

403 Forbidden

CSRF verification failed. Request aborted.

Help

Reason given for failure:

```
CSRF cookie not set.
```

In general, this can occur when there is a genuine Cross Site Request Forgery, or when Django's CSRF mechanism has not been used correctly. For POST forms, you need to ensure:

The view function uses RequestContext for the template, instead of Context.
In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
You're seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.

You can customize this page using the CSRF_FAILURE_VIEW setting.

**Comment by flashingpumpkin** [comment]
As this an issue introduced with the backwards incompatible changes in 1.2 I'll wait until 1.2 hits pypi.

**Comment by flashingpumpkin** [comment]
Hey. There's a new branch 0.3 that includes the CSRF updates for Django 1.2

**Comment by dguaraglia** [comment]
I 'solved' the error by using GET as method to the form. After all we are not changing state on the server, just getting a redirect link.
