### ISSUE TITLE
Column 'identity' cannot be null

### ISSUE THREAD

**Issue by adambossy** [flashingpumpkin/django-socialregistration#10]
Apparently, some open id providers don't return an identity. The two that have failed for me are Blogger and AOL. Simply use the following ids, log in, and it fails when the callback to socialregistration/setup is made.

http://openid.aol.com/{username}
http://{username}.blogspot.com/

I've posted the important parts of the stacktrace here:

http://dpaste.com/hold/157111/

**Comment by flashingpumpkin** [comment]
The new commits fixed that.
