### ISSUE TITLE
What is the difference for callback between OAuth2 example and django-socialregistration 

### ISSUE THREAD

**Issue by cardinal27513** [flashingpumpkin/django-socialregistration#100]
I’m new to the OAuth and trying to make some sense as why I’m seeing the difference when accessing twitter authentication by following the django-socialregistration and example from OAuth2
I’ve the Callback URL setup in twitter as 
“http://127.0.0.1:8000/social/twitter/callback/
Use the following in my template
{% load twitter_tags %}
{% twitter_button %}

Then, after redirected to twitter and click Sign-in.  It calls back and goes to “example.com”. Then resolved to http://www.iana.org/domains/example/

But when I run  “Twitter Three-legged OAuth Example” shown in https://github.com/simplegeo/python-oauth2
It calls back to the link setup in twitter.

Please provide some pointers as what may be goes wrong as I'm still trying figure out the difference in terms of how the underlining is setup. But on surface, it looks similar at least to the point that where the callback is.

Thanks in advance

**Comment by cardinal27513** [comment]
Figured that out.  Socail-registration specifies the callback url in real time and my django site is set to example.com.  Newbie mistake.

**Comment by flashingpumpkin** [comment]
Happy you found out. Was just about to comment on it now, back from holidays. :)
