### ISSUE TITLE
Oauthcallback error with twitter 

### ISSUE THREAD

**Issue by cardinal27513** [flashingpumpkin/django-socialregistration#101]
After clicking Sign-in from Twitter and redirected back to mysite (127.0.0.1)
http://127.0.0.1:8000/social/twitter/callback/?oauth_token=w6rNt0lVPrWKgpOZkCGO1lUdRSJC8XYXxA5mGiA6k&oauth_verifier=0gkTvZhqEkGr33JZwNpwYcWtNZKJSnJDtZ2fN03Hgw
# Getting this error

oauthcallback.html
This is the error template which is shown when a user logs in via OAuth and something goes wrong.
  No request token saved for "api.twitter.com".
# 

Any idea where to look next??

**Comment by flashingpumpkin** [comment]
Yes, socialreg saves the OAuth request token in `request.session['oauth_%s_request_token'] % self.request_token_url`

Have a look at the keys in your session. I reckon, you'll find something like:

`request.session['oauth_twitter.com_request_token']` and not `request.session['oauth_api.twitter.com_request_token']`. Solution might just be to change the twitter url.

**Comment by cardinal27513** [comment]
Here is more info:
It does not work  because, I mix urls with localhost (redirect link ) & 127.0.0.1 (call-back link) and django track that as two different sessions .. therefore, socialreg cannot find the corresponding item in the different session object.  
I added logging to the following functions:
def _get_request_token(self):
    self.request.session['oauth_%s_request_token' % get_token_prefix(self.request_token_url)] = self.request_token
    logger.info("_get_request_token:::session.keys")
    logger.info (id(self.request.session))
    logger.info (self.request.session.keys())

def _get_rt_from_session(self):
    logger.info("_get_rt_from_session:::session.keys")
    logger.info (id(self.request.session))
              logger.info (self.request.session.keys())

When it does not work I see the following:
INFO _get_request_token:::session.keys
INFO 23021360
INFO ['oauth_api.twitter.com_request_token', 'next']

INFO _get_rt_from_session:::session.keys
INFO 23021616
INFO []

There are two diff session objects...
Should there be a way to gurad session object from getting
changed?

**Comment by flashingpumpkin** [comment]
Nah, just use the same URL in your development process.

**Comment by nobyrnes** [comment]
This line in _get_request_token() in utils.py was causing me problems
                    ('oauth_callback', 'http://%s%s' %

In my django site table I had only xxx.com (without the www) so twitter didnt like the redirect.  Simple change is to hack it with the "www"

```
                ('oauth_callback', 'http://www.%s%s' %
```
