### ISSUE TITLE
facebook connect popup doesn't close

### ISSUE THREAD

**Issue by rennat** [flashingpumpkin/django-socialregistration#102]
I'm not familiar with facebook connect and I may be missing something. But I'm in a hurry on this project and don't have time to retrace the whole facebook connect process (which I'd need to learn first.) I'd be grateful for assistance and a quick resolution would definitely be beer money donation worthy.

Anyways, here's the symptoms
- facebook connect window looks correct when the application has no permissions for a user on facebook
- facebook connect window doesnt close automatically when clicking "allow", instead it goes blank with the title XD Proxy
- after manually closing facebook connect window the first time it redirects to `/social/facebook/login` and says there was an error (not specific about what kind of error)
- trying the whole thing again behaves the same until you close the FB window manually, then it goes to `social/login` and asks for username/email
- after submitting then im redirected to my `LOGIN_REDIRECT_URL` correctly
- after logging back out then clicking facebook button the blank XD Proxy window appears again
- when you close it then it redirects properly

I'm gonna jump in and start looking but I'd like to get past this quickly since I'm trying to use it on a quick project i need ready by monday so I'd love to know what I did wrong/didn't do. I've gone over the README instructions and triple checked my settings. I was really hoping for a drop in solution that wouldn't require me to learn how to deal with facebook just yet.

I guess this issue would be with the documentation then, since I ran into this issue someone else probably has too and it's probably because of a setup procedure that was assumed in the documentation.

**Comment by rennat** [comment]
crap... this is only an issue in Chrome. I haven't finished checking but I assume it's an extension interfering

**Comment by flashingpumpkin** [comment]
Chrome extensions are quite often interfering with the Facebook process. I've quite often ran into problems with the Disconnect extension being forgotten and nothing happening. Very annoying. I'm contemplating to switch Facebook using the OAuth workflow too.

**Comment by flashingpumpkin** [comment]
There is no more popup since 0.5
