### ISSUE TITLE
Registration process

### ISSUE THREAD

**Issue by tejinderss** [flashingpumpkin/django-socialregistration#104]
First of all i would like to say sorry for posting this in 'issues' since it is not a bug. I want to ask, i want to create a registration process, so that whenever a user open my site, he will be prompted to create a user account with user id/email and password fields, and he will have the options to retrieve rest of his information from third party sites like facebook/twitter, thus easing the form filling process. Something similar to https://convore.com/. Now i want to ask, does django-socialregistration do that and could you point me to some tutorial to accomplish this task? Thanks.

**Comment by flashingpumpkin** [comment]
There's two ways:
- You override the `setup` view
- You submit a patch where the form is passed the `social_client` parameter (without breaking backwards compatibility): https://github.com/flashingpumpkin/django-socialregistration/blob/master/socialregistration/views.py#L88

The second way would allow you to do all the necessary lookups in the form's `__init__` method.
