### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by tejinderss** [flashingpumpkin/django-socialregistration#105]
getting type error whenever i try to access the facebook template tags or setup view. 
object.**new**() takes no parameters
Request Method: GET
Request URL:    http://192.168.1.5:8000/
Django Version: 1.2.4
Exception Type: TypeError
Exception Value:  
object.**new**() takes no parameters
Exception Location: /home/tejinder/env/local/lib/python2.7/site-packages/django/template/context.py in **init**, line 149
Python Executable:  /home/tejinder/env/bin/python
Python Version: 2.7.1

**Comment by tejinderss** [comment]
Traceback:

Environment:

Request Method: GET
Request URL: http://192.168.1.5:8000/
Django Version: 1.2.4
Python Version: 2.7.1
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.admin',
 'django.contrib.flatpages',
 'analytical',
 'compressor',
 'django_extensions',
 'gunicorn',
 'socialregistration',
 'south',
 'taggit',
 'feeds']
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
 'django.middleware.transaction.TransactionMiddleware',
 'common.middlewares.SetCookieForProtectedEnvironment',
 'common.middlewares.ExceptionUserInfoMiddleware',
 'socialregistration.middleware.FacebookMiddleware')

Traceback:
File "/home/tejinder/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
1.                     response = callback(request, _callback_args, *_callback_kwargs)
   File "/home/tejinder/jobbrew/../jobbrew/apps/home/views.py" in login
2.         {}, context_instance = RequestContext(request))
   File "/home/tejinder/env/local/lib/python2.7/site-packages/django/template/context.py" in **init**
3.             self.update(processor(request))

Exception Type: TypeError at /
Exception Value: object.**new**() takes no parameters

**Comment by flashingpumpkin** [comment]
This seems like an issue not related to socialregistration. Can you post the code to your `jobbrew.apps.home.views.login` function?
