### ISSUE TITLE
Facebook and Logout

### ISSUE THREAD

**Issue by ulucaydin** [flashingpumpkin/django-socialregistration#11]
Hello,

I am using either regular django auth and socialregistration's facebook login for the site and I see an issue with logging out.

I have included <a href="#" onclick="FB.Connect.logoutAndRedirect('{% url auth_logout %}')">Logout</a> as instructed at the readme, however this fails if a user is not logged in via Facebook (just a regular user)

I think for fixing this I need to check if the user is a Facebook account or a Regular one. Sometning like:

```
        {% if facebook_account%}
            (<a href="#" onclick="FB.Connect.logoutAndRedirect('{% url auth_logout %}')">Quit</a>)
        {% else %}
            (<a href="{% url auth_logout %}" >Quit</a>)
        {% endif %}
```

How can I achieve this?

**Comment by ulucaydin** [comment]
It seem to work if I add     'socialregistration.middleware.FacebookMiddleware', to the middleware and check with:

```
        {% if request.facebook.uid %}
            (<a href="#" onclick="FB.Connect.logoutAndRedirect('{% url auth_logout %}')">Logout</a>)
        {% else %}
            (<a href="{% url auth_logout %}" >Logout</a>)
        {% endif %}
```

However it has one big issue, if I login with a regular user of Django (not facebook connected account) and click on logout, it also logs me out from facebook account aswell even tho I didn't even connect to the site using Facebook Connect.

I am wondering how can I check if the account is a facebook proile or a regular account, it seems like {% if request.facebook.uid %} fails for this.

**Comment by girasquid** [comment]
The way that I've done this has been to embed a boolean into the page that tells me whether or not the user has a facebook account associated - the pseudocode is something like "has_facebook_account = FacebookProfile.objects.filter(user=request.user).count() > 0". Poke through the models file to figure out which model you need to filter on, but that should do the trick.

**Comment by ulucaydin** [comment]
Thanks for the idea! This solved the problem well :)
For simplication I have done such:

```
try:
    FacebookProfile.objects.get(user=request.user)
    facebook_acc = True
except:
    facebook_acc = False
```

added this to the context processor file.
