### ISSUE TITLE
AttributeError: 'module' object has no attribute 'parse_signed_request'

### ISSUE THREAD

**Issue by nicksergeant** [flashingpumpkin/django-socialregistration#111]
Upgraded to latest commit (7830f1287b39556000786777f64bf95d410ba190) and get:

```
AttributeError: 'module' object has no attribute 'parse_signed_request'
```

**Comment by nisc** [comment]
First time I've installed django-socialregistration and I get the same error when starting the example project and trying to access /

I'm using the current python-sdk from Github

**Comment by theju** [comment]
From [771ee5199b742488f2b23b0dd5d1883055114fdc] commit message, https://github.com/pythonforfacebook/facebook-sdk needs to be installed.

I think the requirements.txt should be updated in such a case.

**Comment by fahdoo** [comment]
I'm getting this error just now even though this was closed a month ago - does this mean the docs are out of date and I should install the other unofficial facebook-sdk?

**Comment by flashingpumpkin** [comment]
@fahdoo 

I advise using the 0.5 branch out of this repository. It's tested and works with the canonical facebook library. It's backwards incompatible to 0.4 though.
