### ISSUE TITLE
Caught TemplateDoesNotExist while rendering: socialregistration/facebook/facebook_button.html

### ISSUE THREAD

**Issue by zvictor** [flashingpumpkin/django-socialregistration#122]
Why isn't there a default page on the path socialregistration/facebook/facebook_button.html? I don't know what to put in my own facebook_button.html

**Comment by flashingpumpkin** [comment]
See here: https://github.com/flashingpumpkin/django-socialregistration/blob/master/socialregistration/contrib/facebook/templates/socialregistration/facebook/facebook_button.html

**Comment by flashingpumpkin** [comment]
Ah, I'll have to add all the contrib templates to `setup.py`. I normally just copy over all the templates into my project and override them. Sorry, will do asap

**Comment by zvictor** [comment]
Sure. It seems to fix the problem.
I appreciate your attention. Thanks.
