### ISSUE TITLE
error: can't copy 'socialregistration/templates/socialregistration': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by mixman** [flashingpumpkin/django-socialregistration#124]
setup.py seems to have an issue with the template installation.

**Comment by mixman** [comment]
Seems to be fixed by clearing setup.py package_data={} and adding to MANIFEST.in:
recursive-include socialregistration *.html

**Comment by zvictor** [comment]
I confirm the bug.

**Comment by amrox** [comment]
confirmed as well

**Comment by flashingpumpkin** [comment]
Hey, didn't pull your fix in @jeanphix but instead added it all to MANIFEST.in. It's a bit easier on the eyes ;)

See 8dfe49824a7c3f58ec3b053cb9a861fd4cf3de59

**Comment by jeanphix** [comment]
Perfect!
