### ISSUE TITLE
get this characters in my url: #_=_ when login or connect with facebook

### ISSUE THREAD

**Issue by guialante** [flashingpumpkin/django-socialregistration#129]
When I connect or login with facebook at the end of my url I get this characters: #_=_, by example my ulr would look like this: http://mydomain.com/#_=_

How can I fix to my url look normal without this characters.

**Comment by jorilallo** [comment]
This is actually Facebook's fault, don't know what they plan to do with this. I got around it with just Javascript:

```
if (window.location.hash === '#_=_') {
    window.location.hash = '';
}
```
