### ISSUE TITLE
first i had some trouble with the contrib, no module found facebook.. then i discovered that with pip installation i haven't contrib folder. now i have this error:

### ISSUE THREAD

**Issue by caiosv** [flashingpumpkin/django-socialregistration#130]
# ./manage.py runserver

Validating models...

Unhandled exception in thread started by <bound method Command.inner_run of <django.contrib.staticfiles.management.commands.runserver.Command object at 0xb72b9fac>>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 88, in inner_run
    self.validate(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 253, in validate
    raise CommandError("One or more models did not validate:\n%s" % error_text)
django.core.management.base.CommandError: One or more models did not validate:
socialregistration.facebookprofile: Accessor for field 'user' clashes with related field 'User.facebookprofile_set'. Add a related_name argument to the definition for 'user'.
socialregistration.facebookprofile: Accessor for field 'site' clashes with related field 'Site.facebookprofile_set'. Add a related_name argument to the definition for 'site'.
socialregistration.twitterprofile: Accessor for field 'user' clashes with related field 'User.twitterprofile_set'. Add a related_name argument to the definition for 'user'.
socialregistration.twitterprofile: Accessor for field 'site' clashes with related field 'Site.twitterprofile_set'. Add a related_name argument to the definition for 'site'.
socialregistration.linkedinprofile: Accessor for field 'user' clashes with related field 'User.linkedinprofile_set'. Add a related_name argument to the definition for 'user'.
socialregistration.linkedinprofile: Accessor for field 'site' clashes with related field 'Site.linkedinprofile_set'. Add a related_name argument to the definition for 'site'.
socialregistration.openidprofile: Accessor for field 'user' clashes with related field 'User.openidprofile_set'. Add a related_name argument to the definition for 'user'.
socialregistration.openidprofile: Accessor for field 'site' clashes with related field 'Site.openidprofile_set'. Add a related_name argument to the definition for 'site'.
socialregistration.openidstore: Accessor for field 'site' clashes with related field 'Site.openidstore_set'. Add a related_name argument to the definition for 'site'.
openid.openidprofile: Accessor for field 'user' clashes with related field 'User.openidprofile_set'. Add a related_name argument to the definition for 'user'.
openid.openidprofile: Accessor for field 'site' clashes with related field 'Site.openidprofile_set'. Add a related_name argument to the definition for 'site'.
openid.openidstore: Accessor for field 'site' clashes with related field 'Site.openidstore_set'. Add a related_name argument to the definition for 'site'.
twitter.twitterprofile: Accessor for field 'user' clashes with related field 'User.twitterprofile_set'. Add a related_name argument to the definition for 'user'.
twitter.twitterprofile: Accessor for field 'site' clashes with related field 'Site.twitterprofile_set'. Add a related_name argument to the definition for 'site'.
linkedin.linkedinprofile: Accessor for field 'user' clashes with related field 'User.linkedinprofile_set'. Add a related_name argument to the definition for 'user'.
linkedin.linkedinprofile: Accessor for field 'site' clashes with related field 'Site.linkedinprofile_set'. Add a related_name argument to the definition for 'site'.
facebook.facebookprofile: Accessor for field 'user' clashes with related field 'User.facebookprofile_set'. Add a related_name argument to the definition for 'user'.
facebook.facebookprofile: Accessor for field 'site' clashes with related field 'Site.facebookprofile_set'. Add a related_name argument to the definition for 'site'.

**Comment by acarpentier** [comment]
Same for me here

**Comment by flashingpumpkin** [comment]
This was due to unused models being imported. See #128
