### ISSUE TITLE
Get first and last name

### ISSUE THREAD

**Issue by socksz** [flashingpumpkin/django-socialregistration#137]
Hi,
I added these lines [here](https://github.com/flashingpumpkin/django-socialregistration/blob/master/socialregistration/views.py#L125):

```
graph = request.facebook.graph 
fb_profile = graph.get_object("me")
user.first_name = fb_profile['first_name']
user.save()
```

When I try to connect I get this error: `int() argument must be a string or a number, not 'AnonymousUser'`.
Why?

**Comment by flashingpumpkin** [comment]
The graph will be removed due to Facebook dropping support for their "official" python sdk

**Comment by flashingpumpkin** [comment]
But, presumably, you've tried to save an `AnonymousUser` instead of creating a new `User()`?

**Comment by flashingpumpkin** [comment]
Looked at it again.

You're definitely trying to save an anonymous user. The user will only be a regular Django user _after_ [the call to login](https://github.com/flashingpumpkin/django-socialregistration/blob/master/socialregistration/views.py#L128)
