### ISSUE TITLE
conflict w/ tables created

### ISSUE THREAD

**Issue by aljosa** [flashingpumpkin/django-socialregistration#148]
after clean install, syncdb and migrate tables created for socialregistration:
facebook_facebookaccesstoken
facebook_facebookprofile
socialregistration_facebookaccesstoken
socialregistration_facebookprofile

would not be a problem but code generates sql that is trying to access facebook_\* tables.
this is 0.5.4 from pypi and i've used 0.4.x before w/o this problem, any idea what i'm doing wrong?

**Comment by aljosa** [comment]
adding to fb profile and accesstoken in models.py resolves this issue for me:

```
class Meta:
    db_table = "socialregistration_facebookprofile"

class Meta:
    db_table = "socialregistration_facebookaccesstoken"
```

**Comment by flashingpumpkin** [comment]
This shouldn't happen any more as I removed all models from `socialregistration.models`. Closing.
