### ISSUE TITLE
Facebook, retrieving users first and last name

### ISSUE THREAD

**Issue by ulucaydin** [flashingpumpkin/django-socialregistration#15]
How can I retrieve users first and last names while he is connected with Facebook? It seems like the code itself doesn't provide tools to achieve this.

Regards

**Comment by aljosa** [comment]
you can use pyfacebook, something like:

> > > request.facebook.users.getInfo([facebook_uid,], ['first_name', 'last_name'])

**Comment by vallettea** [comment]
and where do you put this?

**Comment by aljosa** [comment]
you could use it in views or anywhere where you can access request.

also, facebook released python sdk http://github.com/facebook/python-sdk

**Comment by vallettea** [comment]
thanks!
but for the "python-sdk"... you recommend to use it as an example to tune socialregistration or to reimplement facebook authentication?

i'm a bit lost because i don't see any thing like "request.facebook.users.getInfo" in the appengine...

**Comment by aljosa** [comment]
django-socialregistration doesn't use pyfacebook anymore, it uses official python-sdk.

try using "request.facebook.graph", you should be able to access graph from python-sdk and use python-sdk api.
note that facebook user needs to be logged in to use request.facebook.graph
