### ISSUE TITLE
Django 1.4 and path problems

### ISSUE THREAD

**Issue by zvictor** [flashingpumpkin/django-socialregistration#151]
I use dotcloud and I updated to Django 1.4 recently.
Now, to things work, I need to change socialregistration/contrib/facebook/client.py in line 7, from "import facebook" to "from socialregistration.contrib import facebook".

The question is: Should this app update its code, or should dotcloud change something on paths?
I am creating an issue there too.

**Comment by flashingpumpkin** [comment]
`import facebook`  is actually Facebook's old Python SDK. Unfortunately they pulled that finally from their Github account. However, I've still got a copy of it [here](https://github.com/flashingpumpkin/facebook-sdk-fork). But the idea is to clean up the code and remove this dependency. 

Also while at it I should remove `httplib2` and replace it with `requests`.

**Comment by zvictor** [comment]
Yeah, I made a confusion. Sorry

from Dotcloud's support:
"It looks like Facebook has dropped support for their official Python client[1](http://developers.facebook.com/bugs/200182333402545/), upon which django-socialregistration depends[2](http://django-socialregistration.readthedocs.org/en/latest/installation.html#installation). Facebook's decision to suddenly remove the library from github, seems to have caused problems for other django-socialregistration users too[3](http://stackoverflow.com/questions/8533065/have-facebook-dropped-support-for-python). In the short term, your best bet is probably to try using one of available mirrors of the original Facebook library[4](https://github.com/flashingpumpkin/facebook-sdk-fork), but I can't guarantee that will work, so a better long-term solution woulb be getting in contact with the django-socialregistration maintainers to update/remove the dependency (or at least fix the docs).

Hope that helps!
-Gabriel

"
