### ISSUE TITLE
Custom Setup views

### ISSUE THREAD

**Issue by ibustama** [flashingpumpkin/django-socialregistration#152]
I was just making a custom Setup view, and was wondering about the way to pass in a custom form. 

If you're already customizing the Setup view (by extending from socialregistration.views.Setup), shouldn't you just have to override a form attribute within your custom view class, instead of indicating it in the SOCIALREGISTRATION_SETUP_FORM in settings or having to redefine the get_form() function? I can make a patch for this, but I'm not sure if there's a reason why this works this way.

**Comment by flashingpumpkin** [comment]
Hi

Depends. If you just need custom form validation, use `SOCIALREGISTRATION_SETUP_FORM`. If you need custom logic to determine which form to use (or similar), use `get_form`. Eg (pseudocode):

``` python
if self.twitter: return TWITTER_FORM
else: return STANDARD_FORM
```

**Comment by ibustama** [comment]
Oh I see now. I was just wondering if it was a design decision. Thanks for replying =)
