### ISSUE TITLE
Need to update requirement for Django version

### ISSUE THREAD

**Issue by newptcai** [flashingpumpkin/django-socialregistration#157]
In "socialregistration/views.py", line 5 is

```
from django.views.generic.base import View 
```

This module `django.views.generic.base` doesn't exist in Django 1.1.4

But when you install socialregisteration with pip, it doesn't complain about requirement not fulfilled.

**Comment by flashingpumpkin** [comment]
Hi

I've removed dependencies to Django a while ago to not interfere with your installed Django version (and most other packages don't do it). 

I've outlined which versions of socialreg work with which Django versions in #145 but in any case I recommend upgrading to at least Django 1.3.1 as iirc it's compatible with Django 1.1. 

In any case, I'll have to document the versions. 

Alen
