### ISSUE TITLE
using socialregistration in fb canvas app?

### ISSUE THREAD

**Issue by aljosa** [flashingpumpkin/django-socialregistration#16]
i'm trying to use socialregistration to authorize fb users for fb canvas app and sometimes it works sometimes not.
has anyone used socialregistration for fb canvas app?

i think most issues are somehow related to cookie, browser cache and other iframe situations.
i have most issues with webkit based browsers but others have issues also.

**Comment by flashingpumpkin** [comment]
Hey

No - I've never done a canvas app. Facebook Connect is not intended for canvas apps but apps that live outside of  Facebook. If you're doing a pure canvas app, I sugges you look up the python/django howto in Facebooks dev wiki
