### ISSUE TITLE
Credentials could not be validated, the provider returned no access token. (getting this all the time)

### ISSUE THREAD

**Issue by TamaraAtanasoska** [flashingpumpkin/django-socialregistration#160]
I explained all I know on stackoverflow: http://stackoverflow.com/questions/11134973/cant-log-in-to-facebook-django-socialregistration/11135264 about this error.

You can reproduce the error yourself, here is a link from the site in development http://republikamladi.reactororg.webfactional.com/debate/2/

Twitter works fine, though.

Can you help?

**Comment by flashingpumpkin** [comment]
One other issue I can think of: Is the app on Facebook in development mode? If I remember correctly only admins can authenticate against applications in development mode. Other than that, I'm hesitant to add the whole dictionary that is returned into the raised `OAuthError` - but obviously that would help track it down: 7d0a281b764cfb8b821860a67335e4d0ea553780

**Comment by TamaraAtanasoska** [comment]
Credentials could not be validated, the provider returned no access token: {} - It is empty

**Comment by flashingpumpkin** [comment]
This is odd. Can you step through the code an have a look at the raw response returned from Facebook?

Eg, add

``` python
import pdb; pdb.set_trace()
```

at [line 268 in oauth.py](https://github.com/flashingpumpkin/django-socialregistration/blob/7d0a281b764cfb8b821860a67335e4d0ea553780/socialregistration/clients/oauth.py#L268) and inspect `content`.

**Comment by TamaraAtanasoska** [comment]
BdbQuit at /social/facebook/callback/
No exception supplied

This was returned if I did it the right way.

**Comment by flashingpumpkin** [comment]
You quit out of the debugger. 

When the execution hits the pdb statement you should be dropped into a shell that is pretty similar to Python's - except that it offers commands to inspect the current context. When dropping into the debugger, you can type `help` to get a list of supported commands. `q` will escape the further execution of the current request. To inspect the content just do `print content`.

**Comment by TamaraAtanasoska** [comment]
Oh, I have never imported my project into python shell before so I have no idea how to do that. I will look for a way now and get back to you.

**Comment by TamaraAtanasoska** [comment]
Ok, I realized I can't do that since I deployed your application directly on the server. So I will have to install it locally to do that too. That will take some time I guess :)

**Comment by TamaraAtanasoska** [comment]
So I figured the problem that night but I forgot to post back. I had FACEBOOK_API_SECRET instead of FACEBOOK_SECRET_KEY. 
I also had to add single quotation marks around few contrib/facebook/templates/socialregistration/facebook/facebook_button.html of these templates, at this line 
{% url 'socialregistration:facebook:redirect' %}, so check that :)

I now have a different question, why the requested permissions doesn't get saved somewhere in the database? Or I have to code that myself?

**Comment by flashingpumpkin** [comment]
Hi

Glad you solved it. Yes - socialreg does not keep track of what 
permissions got granted. But there are signals which you can utilise to 
do that.

**Comment by ajithpmohan** [comment]
Hi, I also have the same issue in django-social-registration. I cant fix this. Access token missing after
content = self.parse_access_token(content) in oauth.py file with line no 294.

Itz working fine until last week. Till get Above mentioned error( OAuthError: Credentials could not be validated, the provider returned no access token)

Can Someone Help?
