### ISSUE TITLE
openid service bug with mysql

### ISSUE THREAD

**Issue by snird** [flashingpumpkin/django-socialregistration#163]
(Sorry for my English)

the bug seems related to this Django bug:
https://code.djangoproject.com/ticket/2495

needs a workaround. 
as i deleted the "unique=True" attr from contrib.openid.models at "identity" in OpenIDProfile it fixed.
without it, the syncdb don't pass the verification.

**Comment by flashingpumpkin** [comment]
Fixed with #168, thanks for reporting
