### ISSUE TITLE
Session Expired

### ISSUE THREAD

**Issue by nzee** [flashingpumpkin/django-socialregistration#165]
While clicking on facebook button it takes me to a blank page with "Session Expired" message. Why is it?

**Comment by flashingpumpkin** [comment]
This might be for a number of reasons. The most likely is that you initialize the connection process from a different domain than the callback URL. There is a [note on sessions](http://django-socialregistration.readthedocs.org/en/latest/installation.html#note-on-sessions) in the documentation. If that is not the case I would need more information on your setup.
