### ISSUE TITLE
Django TransactionTestCase fails with socialregistration and south

### ISSUE THREAD

**Issue by heyman** [flashingpumpkin/django-socialregistration#166]
A django project that uses both socialregistration and south can not use Django's TransactionTestCase without getting the following error when running the tests:

```
Error: Database test_quail couldn't be flushed. Possible reasons:
  * The database isn't running or isn't configured correctly.
  * At least one of the expected database tables doesn't exist.
  * The SQL was invalid.
Hint: Look at the output of 'django-admin.py sqlflush'. That's the SQL this command wasn't able to run.
The full error: cannot truncate a table referenced in a foreign key constraint
DETAIL:  Table "socialregistration_facebookprofile" references "django_site".
HINT:  Truncate table "socialregistration_facebookprofile" at the same time, or use TRUNCATE ... CASCADE.
```

The reason for this is that socialregistration's south migrations creates the above tables that are no longer used (since the models seems to have been moved into the standalone contrib apps), but there are no migrations that renames/deletes them.

A possible workaround to get the tests to run is to disable south when running the test suite, but this isn't desirable since then it's easy to miss migration  dependency issues.

Currently, as a workaround, I've added a migration in my project that deletes the unused socialregistration tables:

``` python
class Migration(SchemaMigration):
    depends_on = (
        ("socialregistration", "0004_auto__add_linkedinprofile__add_linkedinrequesttoken__add_linkedinacces"),
    )

    def forwards(self, orm):
        db.delete_table("socialregistration_facebookaccesstoken")
        db.delete_table("socialregistration_facebookprofile")
        db.delete_table("socialregistration_linkedinaccesstoken")
        db.delete_table("socialregistration_linkedinprofile")
        db.delete_table("socialregistration_linkedinrequesttoken")
        db.delete_table("socialregistration_openidnonce")
        db.delete_table("socialregistration_openidprofile")
        db.delete_table("socialregistration_openidstore")
        db.delete_table("socialregistration_twitteraccesstoken")
        db.delete_table("socialregistration_twitterprofile")
        db.delete_table("socialregistration_twitterrequesttoken")

    def backwards(self, orm):
        pass
```

**Comment by flashingpumpkin** [comment]
I am a bit wary of adding this migration to socialreg. I've left the migrations in the code when doing the jump from 0.4 to 0.5 for people to be able to migrate the data to the new tables. I wouldn't want them to lose all their data when next upgrading. :)

What I can do though is kicking out the migrations with a new version bump.
