### ISSUE TITLE
I keep getting "Caught AttributeError while rendering: Please add the ``django.core.context_processors.request`` context processors to your settings.CONTEXT_PROCESSORS set"

### ISSUE THREAD

**Issue by saevarom** [flashingpumpkin/django-socialregistration#17]
I have a very basic view to test fb connect:

```
def fbtest(request):
    return render_to_response('fbtest.html',context_instance=RequestContext(request))
```

and I have 

```
    TEMPLATE_CONTEXT_PROCESSORS = ('django.core.context_processors.request',)
```

in settings.py

What am I doing wrong? The documentation for this app is very limited as it provides no examples or demos of some sort.

**Comment by flashingpumpkin** [comment]
Hey

Can you provide a bit more context? For example the contents of `fbtest.html` 

This exception is only raised if there is no `context['request']` object to be found in the various twitter/facebook/openid tags.

**Comment by saevarom** [comment]
fbtest.html looks like this:

```
{% load facebook_tags %}
{% facebook_button %}
{% facebook_js %}
```

**Comment by virtuallight** [comment]
The problem lays for example inside facebook_button function from facebook_tags. In place of
    if not 'request' in context
type
    if not context.has_key('request')
I'm using Django 1.1. Might there be some changes that they made to the context object in the past?

**Comment by flashingpumpkin** [comment]
Interesting. Saevarom, would this fix your issue?

It might as well be interesting to know which python version you're running on.

Also, skip the `{% facebook_button %}` and just try a `{{ request|pprint }}` to see if there is actually the request object in your context.

**Comment by virtuallight** [comment]
This is so crazy but I can't reproduce it now. I'm using Python 2.5.4 and Django 1.1.1 and I am 100% sure I haven't been using anything else lately. It might have been caused by some middleware juggling or some broken python/django packages installation. Both happend at that the same day... but I doubt that I was it.

So only Saevarom can help You now if he still can produce that error.

**Comment by saevarom** [comment]
I'm using Python 2.6.4rc2

I can get rid of this error by simply setting the defaults of TEMPLATE_CONTEXT_PROCESSORS before adding the request context processor. Defaults are mentioned here: http://docs.djangoproject.com/en/dev/ref/settings/#template-context-processors

But the tags don't produce any output. I have put the socialregistration template directory in my templates directory but no luck :(

**Comment by flashingpumpkin** [comment]
What about the form tags? Are they missing from your templates too?

**Comment by swbiggart** [comment]
I was having the same issue until I found this page:

http://lincolnloop.com/blog/2008/may/10/getting-requestcontext-your-templates/

So, if you are just using the render_to_response shortcut, you need something like this in your views.py file:
    from django.shortcuts import render_to_response
    from django.template import RequestContext

```
def login(request):
    return render_to_response('login.html', 
                              {}, 
                              context_instance=RequestContext(request))
```

where login.html is the template where you are using the

```
{% load facebook_tags %}
{% facebook_button %}
{% facebook_js %}
```

There are additional examples on how to pass the RequestContext if you are not using the django generic views (which pass the RequestContect by default) on the above linked page.

**Comment by rakyll** [comment]
I'm still having the same problem and {{ request|pprint }} returns me ''

**Comment by flashingpumpkin** [comment]
@burcu

that means you don't have the context processors set correctly and the request object is not passed into the template.

**Comment by rakyll** [comment]
I fixed the issue. A bug on a third party component I was using were blocking the request object somehow and request object ends up with not having the attributes socialregistration is looking for. That's how I got the exception.

**Comment by IanWhalen** [comment]
Burcu, could you clarify what third party component you were using and what you ended up doing to resolve the problem?

**Comment by dbrgn** [comment]
Could you please include the note by @swbiggart in the documentation? It would have helped me a lot (in the end, I found the same answer on Github).
