### ISSUE TITLE
Build Problem - Missing README.rst on tarball

### ISSUE THREAD

**Issue by aledr** [flashingpumpkin/django-socialregistration#18]
Here is the error I got.

/usr/bin/python setup.py build
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    long_description=open('README.rst').read(),
IOError: [Errno 2] No such file or directory: 'README.rst'
error: Bad exit status from /var/tmp/rpm-tmp.4HD1xq (%build)

Thanks.

**Comment by flashingpumpkin** [comment]
Which tarball?

**Comment by flashingpumpkin** [comment]
Ah, okay - that escaped my attention. I was downloading the tag files on github instead of pypi.

**Comment by aledr** [comment]
The PyPI one.

**Comment by flashingpumpkin** [comment]
Yep. Fixed and changed the archive on PyPI
