### ISSUE TITLE
Error rendering the template | Invalid block tag: 'csrf_token'

### ISSUE THREAD

**Issue by nooscraft** [flashingpumpkin/django-socialregistration#19]
Invalid block tag: 'csrf_token'

1  
2   <form class="connect-button" name="login" method="post" action="{% if logged_in %}{% url facebook_connect %}{% else %}{% url facebook_login %}{% endif %}">
3   {% csrf_token %}
4   {% if next %}
5   <input type="hidden" name="next" value="{{ next }}" />
6   {% endif %}
7   <input type="image" onclick="facebookConnect(this.form);return false;" src="http://static.ak.fbcdn.net/images/fbconnect/login-buttons/connect_light_large_long.gif" />
8   </form>

Django version:- 1.1.1
Python version:- 2.6.2

**Comment by gvangool** [comment]
This is a new template tag in 1.2. It should be in the last/next 1.1 release.

**Comment by nooscraft** [comment]
I have the latest django release

**Comment by gvangool** [comment]
You can switch to the [1.1 branch](http://code.djangoproject.com/browser/django/branches/releases/1.1.X) or wait for the 1.1.2 release, which will be released together with 1.2.

**Comment by flashingpumpkin** [comment]
This is fixed. I've added a wrapper around `{% csrf_token %}` which figures out if there is the need for it or not.
