### ISSUE TITLE
xd_receiver.htm vs xd_receiver.html

### ISSUE THREAD

**Issue by mcbride** [flashingpumpkin/django-socialregistration#2]
I'm getting an error from facebook calling back for xd_receiver.htm, but the urls line

http://github.com/flashingpumpkin/django-socialregistration/blob/master/socialregistration/urls.py

is catching ^xd_receiver.html$. I think this is a change on facebook and html use to be correct. Changing the regex to ^xd_receiver.htm fixed the problem. See

http://wiki.developers.facebook.com/index.php/Cross_Domain_Communication_Channel

**Comment by flashingpumpkin** [comment]
Updated
