### ISSUE TITLE
Experiencing TemplateSyntaxError 

### ISSUE THREAD

**Issue by nooscraft** [flashingpumpkin/django-socialregistration#20]
Caught an exception while rendering: Tried xd_receiver in module myfirstapp.fbapp.views. Error was: 'module' object has no attribute 'xd_receiver'

1   <script src="http://static.ak.connect.facebook.com/js/api_lib/v0.4/FeatureLoader.js.php/en_US" type="text/javascript"></script>
2   <script type="text/javascript">
3   FB_RequireFeatures(["XFBML"],
4   function() {
5   FB.Facebook.init("{{ facebook_api_key }}", "{% url facebook_xd_receiver %}")
6   }
7   );
8   function facebookConnect(form){
9   FB.Connect.requireSession();
10  FB.Facebook.get_sessionState().waitUntilReady(
11  function(){
12  form.submit();
13  }
14  );
15  }

**Comment by flashingpumpkin** [comment]
Did you include the socialregistration urls? Please refer to the PM i've sent you
