### ISSUE TITLE
[Request] New Login with Facebook

### ISSUE THREAD

**Issue by jorilallo** [flashingpumpkin/django-socialregistration#22]
Any change to move using the new Facebook API? Documentation seems pretty easy and I would love to see this as part of django-socialregistration workflow:

http://developers.facebook.com/docs/guides/web#login

And it would be cool if this would support new Python SDK by Facebook:

http://github.com/facebook/python-sdk

Things I would like to see:
- Extended permission (could set in settings.py which ones I need) 
- Make .js stuff work that it's easy to use same code with social objects (e.g. 'Like' box) 
- Support for Django 1.1.x <3

Any plans to support?

**Comment by flashingpumpkin** [comment]
Yes, I've had a look at the new library yesterday. I'll move it soonish, when I get some spare time to do so.

**Comment by jorilallo** [comment]
Cool :)

**Comment by flashingpumpkin** [comment]
Done.
