### ISSUE TITLE
user.is_authenticated doesn't work in RequestContext templates for local users

### ISSUE THREAD

**Issue by LukeNukem** [flashingpumpkin/django-socialregistration#26]
Unfortunately, user.is_authenticated does not work for a template in a RequestContext when I'm logged in as a local (not facebook) user. I've had to create a new template variable "req" with the request in it and then use req.user.is_authenticated in my template. Have i missed the docs?

**Comment by flashingpumpkin** [comment]
If you add the `django.core.context_processors.request` context processor to your `TEMPLATE_CONTEXT_PROCESSORS` settings, you'll have a `request` object available in all your templates. That is, if you go use the `context_instance`.

```
def view(request):
    #...
    return render_to_response('template.html', dict(), 
        context_instance = django.template.context.RequestContext(request))
```

**Comment by LukeNukem** [comment]
That'll give me a 'request' object in my template, but I'd rather have a 'user' and a 'perms' object like in django.template.RequestContext. Thus, I'd want to use {% if user.is_authenticated %} rather than {% if request.user.is_authenticated %} in my templates. Is that possible?

**Comment by LukeNukem** [comment]
Solved. I had forgotten to re-add django.core.context_processors.auth to TEMPLATE_CONTEXT_PROCESSORS. Doh, seems I'd missed the docs indeed. Sorry for asking a silly question -- and thank you for your your time and patience answering it.
