### ISSUE TITLE
facebook canvas/iframe support

### ISSUE THREAD

**Issue by aljosa** [flashingpumpkin/django-socialregistration#27]
i've modified middleware.py so that i can use socialregistration in facebook canvas/iframe.
with this change in middleware and call to facebook_login() socialregistration works in facebook canvas/iframe (some additional code is required to fix cookie problems in IE and Safari).
i was wondering if this code (or any code that works for facebook canvas/iframe) could eventually end in socialregistration?

class FacebookMiddleware(object):
    def process_request(self, request):

```
    if 'session' in request.GET:
        session = request.GET.get('session')
        data = json.loads(session)
        request.facebook = Facebook(data)
        return None

    fb_user = facebook.get_user_from_cookie(request.COOKIES,
        settings.FACEBOOK_API_KEY, settings.FACEBOOK_SECRET_KEY)

    request.facebook = Facebook(fb_user)
    return None
```

**Comment by flashingpumpkin** [comment]
I'd have to try it out. Never built a canvas / iframe application and I'm a bit short on time.
