### ISSUE TITLE
Retrieve facebook profile image

### ISSUE THREAD

**Issue by guialante** [flashingpumpkin/django-socialregistration#28]
How can I retrieve facebook profile image using facebook.GraphAPI ??? thanks

**Comment by flashingpumpkin** [comment]
Hey. 

Have a look at Facebook's documentation here: 
http://developers.facebook.com/docs/api
http://developers.facebook.com/docs/api#pictures

And have also a look at the documentation of the new SDK here:
http://github.com/facebook/python-sdk
