### ISSUE TITLE
With Twitter it always ask for authorization

### ISSUE THREAD

**Issue by estebanfeldman** [flashingpumpkin/django-socialregistration#29]
When I try to make twitter work, it always ask me for Authorization, even when I already authorized it already, I was looking at the code but is too late now. But I think it has to do with the OAuthClient that always asks for the _get_authorization_url.

**Comment by estebanfeldman** [comment]
Changed:

TWITTER_AUTHORIZATION_URL = 'http://twitter.com/oauth/authorize'

for

TWITTER_AUTHORIZATION_URL = 'http://twitter.com/oauth/authenticate'

**Comment by cyberkishor** [comment]
it's still not working for my module... 
what is the problem... any body ... help me?
