### ISSUE TITLE
'ModPythonRequest' object has no attribute 'facebook'

### ISSUE THREAD

**Issue by adambossy** [flashingpumpkin/django-socialregistration#3]
I'm able to set up a page for Facebook authentication. I see the Facebook button, click on it, and I'm taken to the Facebook Connect dialog. After logging in, I am returned to my site with the path "/djroot/accounts/facebook/login/". I get an Attribute Error on this page: 

AttributeError at /accounts/facebook/login/
'ModPythonRequest' object has no attribute 'facebook'
...
Traceback 

/var/lib/python-support/python2.5/django/core/handlers/base.py in get_response  
86.   response = callback(request, _callback_args, *_callback_kwargs) 

/usr/lib/python2.5/site-packages/django_socialregistration-0.2-py2.5.egg/socialregistration/views.py in facebook_login
102.  if not request.facebook.check_session(request): 

I'm running Python 2.5.2 and Django 1.0. Any ideas?

**Comment by flashingpumpkin** [comment]
http://wiki.developers.facebook.com/index.php/User:PyFacebook_Tutorial#Add_the_middleware

I'll add this information to the readme.

**Comment by adambossy** [comment]
Bingo! Thanks for the quick response!
