### ISSUE TITLE
facebook-python-sdk issue

### ISSUE THREAD

**Issue by fahdoo** [flashingpumpkin/django-socialregistration#31]
So I'm trying to get django-socialregistration to work with my new django project and I have a few questions (I'm also a django n00b):

1) Can I use it without using django-registration?

2) Does this create the user tables at all cause I don't have any authentication or user model whatsoever. Kind of tied to (1) I guess

3) One of the dependencies is the facebook-python-sdk but it has no easy_install. I git cloned it, and then installed it. I see it in my /lib/python2.6 but it seems that django doesn't know it exists. I also don't see it under the /lib/python2.6/easy-install.pth. I do see it when I do "yolk -l". Basically the error I get when I load my project in the browser is "Please make sure you have _facebook.djangofb.FacebookMiddleware_ installed as a middleware." When I put it in the middleware it 500s and the error_log shows that it doesn't know what djangofb is. Also, "facebook.djangofb.FacebookMiddleware" isn't supposed to be there according to the django-socialregistration docs because I have 'socialregistration.middleware.FacebookMiddleware'.

FYI, I'm using webfaction as my host.

**Comment by flashingpumpkin** [comment]
> 1) Can I use it without using django-registration?

Yes

> 2) Does this create the user tables at all cause I don't have any authentication or 
> user model whatsoever. Kind of tied to (1) I guess

No. But, if you're using django.contrib.auth, you'll get user and group models. This is actually a dependency of django-socialregistration. Have a look at the documentation:
http://docs.djangoproject.com/en/1.2/topics/auth/#topics-auth

> 3) One of the dependencies is the facebook-python-sdk but it has no easy_install. I git 
> cloned it, and then installed it.

That's right for the master and 0.4 branch. Everything below that relies on `pyfacebook` (http://github.com/sciyoshi/pyfacebook)
Though, you might want to look into `pip`. You can install arbitrary packages with it like that:
`pip install -e git+http://github.com/facebook/python-sdk.git#egg=facebook` 

> When I put it in the middleware it 500s and the error_log shows that it doesn't know 
> what djangofb is. Also, "facebook.djangofb.FacebookMiddleware" isn't supposed to 
> be there according to the django-socialregistration docs because I have 
> 'socialregistration.middleware.FacebookMiddleware'.

I guess you installed it from http://pypi.python.org which currently sports the 0.3.x version, which in turn depends on `pyfacebook`. I'll upload the 0.4 version today.

> FYI, I'm using webfaction as my host.

There's a site I'm aware of that runs socialregistration on Webfaction, so all should be fine. 

PS: You might also want to look into `virtualenv` if you don't know that yet.
