### ISSUE TITLE
pypi package broken

### ISSUE THREAD

**Issue by mixman** [flashingpumpkin/django-socialregistration#33]
<pre>

sh-3.2# pip install django-socialregistration
Downloading/unpacking django-socialregistration
  Downloading django-socialregistration-0.4.1.tar.gz
  Running setup.py egg_info for package django-socialregistration
    package init file 'socialregistration/__init__.py' not found (or not a regular file)
    error: package directory 'socialregistration/templatetags' does not exist
    Complete output from command python setup.py egg_info:
    running egg_info

creating pip-egg-info/django_socialregistration.egg-info

writing requirements to pip-egg-info/django_socialregistration.egg-info/requires.txt

writing pip-egg-info/django_socialregistration.egg-info/PKG-INFO

writing top-level names to pip-egg-info/django_socialregistration.egg-info/top_level.txt

writing dependency_links to pip-egg-info/django_socialregistration.egg-info/dependency_links.txt

writing manifest file 'pip-egg-info/django_socialregistration.egg-info/SOURCES.txt'

warning: manifest_maker: standard file '-c' not found

package init file 'socialregistration/__init__.py' not found (or not a regular file)

error: package directory 'socialregistration/templatetags' does not exist

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in ./pip-log.txt
</pre>

**Comment by flashingpumpkin** [comment]
Updated and replaced the packages with `find_packages`
