### ISSUE TITLE
Session is lost at twitter callback

### ISSUE THREAD

**Issue by vsaase** [flashingpumpkin/django-socialregistration#34]
Facebook login works fine, so I think this has to be something special to Twitter:

When getting redirected to oauth_callback from Twitter, django creates a new session and therefore cannot find the request token in it.

Is it possible that Twitter somehow messes up my cookie?

**Comment by flashingpumpkin** [comment]
Hm.. did you check your browser settings?

**Comment by EugeneLiang** [comment]
i am facing the same issue too. so what are the things do i have to check?

**Comment by vsaase** [comment]
Ok, it turned out that I was using 'localhost' when redirecting to twitter and the callback went to '127.0.0.1', so the browser did not use the previous cookie that was associated with 'localhost'.

**Comment by EugeneLiang** [comment]
i've tested out on a working site, but after logging in with Twitter, no cookies are being set or whatever. it seems that the session is lost.

**Comment by vallettea** [comment]
same problem

**Comment by cpauya** [comment]
For Twitter, I use 127.0.0.1:8000... on the callback url, then set the Sites' domain value to 127.0.0.1:8000 - using 'localhost' does not work with me.

**Comment by zerok** [comment]
I'm not completely positive on that yet but to me it looks like that oauth_callback is set for the wrong token and therefor never really recognized by Twitter. Shouldn't the callback be included in the request for the request_token and not just appended to the auth request URL?

**Comment by flashingpumpkin** [comment]
You are right @zerok. 
http://tools.ietf.org/html/rfc5849 describes the callback to be passed to the auth server when creating the `oauth_token`

Weirdly enough, all the pages that we're running don't seem to have auth problems with twitter.

**Comment by zerok** [comment]
@flashingpumpkin: Could it be that you have set the same URL you pass as callback as the default callback in the twitter panel? To me it looks like Twitter is kind of mixing OAuth 1.0 and 1.0a :-/ Anyway: I've already created another ticket with #GH-52 (as you've already noticed :-) ) since this might be unrelated.
