### ISSUE TITLE
AttributeError : 'module' object has no attribute 'get_user_from_cookie'

### ISSUE THREAD

**Issue by EugeneLiang** [flashingpumpkin/django-socialregistration#37]
Hi, 
I have installed socialregistration, pyfacebook, facebook-python-sdk, sciyoshi-pyfacebook, and http://github.com/facebook/python-sdk/.

After all the setup, i am receiving weird errors: AttributeError : 'module' object has no attribute 'get_user_from_cookie'

The exception location is at : Exception Location:  /usr/local/lib/python2.6/dist-packages/django_socialregistration-0.4.2-py2.6.egg/socialregistration/middleware.py in process_request, line 23

I am testing out on a website, you can have a look at www.tabbing.me/rapidtask/

May I know if its a bug?

**Comment by kennethlove** [comment]
Yeah, this hit me too. What's the solution?

**Comment by dziegler** [comment]
This is an import error. The facebook python-sdk and pyfacebook both use `import facebook`, so having them both installed will create problems. It looks like this is picking up pyfacebook first in the import path. If you do 

```
import facebook
print facebook.__path__
```

it'll show you where it's picking up the import

**Comment by EugeneLiang** [comment]
i see. so which should it be importing for it to work? python-sdk or pyfacebook?

**Comment by dziegler** [comment]
If it's looking for get_user_from_cookie, it should be importing python-sdk

**Comment by shacker** [comment]
What worked for me:

pip uninstall pyfacebook

Then re-install python-sdk:

pip install git+git://github.com/facebook/python-sdk.git
