### ISSUE TITLE
Error: Caught NoReverseMatch while rendering: Reverse for 'facebook_connect' with arguments '()' and keyword arguments '{}' not found.

### ISSUE THREAD

**Issue by timothyjoelwright** [flashingpumpkin/django-socialregistration#38]
When adding {% facebook_button %} to my template I get the error:
Caught NoReverseMatch while rendering: Reverse for 'facebook_connect' with arguments '()' and keyword arguments '{}' not found.

1   {% load socialregistration_tags %}
2   {% comment %}
3   <fb:login-button autologoutlink="true" perms="email,user_birthday,status_update,publish_stream">/fb:login-button
4   {% endcomment %}
5  
6   <form class="connect-button" name="login" method="post" action="{% if logged_in %}{% url facebook_connect %}{% else %}{% url facebook_login %}{% endif %}">
7   {% social_csrf_token %}
8   {% if next %}
9       <input type="hidden" name="next" value="{{ next }}" />
10  {% endif %}
11  <input type="image" onclick="facebookConnect(this.form);return false;" src="http://static.ak.fbcdn.net/images/fbconnect/login-buttons/connect_light_large_long.gif" />
12  </form>
13

**Comment by timothyjoelwright** [comment]
My bad - I didn't have my urls configured correctly. Perhaps a clear example of what to add to urls.py would be helpful for super noobs like myself. :) Thanks!

**Comment by ghost** [comment]
Well I'm stuck here myself. Mind saying how you fixed it?

**Comment by ghost** [comment]
<form class="connect-button" name="login" method="post" action="{% if logged_in %}{% url facebook_connect %}{% else %}{% url facebook_login %}{% endif %}"> 
 is where it throws the error. I'm importing my urls like so:
from socialregistration.urls import *

**Comment by dbrgn** [comment]
@paperino: The correct way would be:

```
(r'^social/', include('socialregistration.urls')),
```

@flashingpumpkin, please include this in the docs.

**Comment by flashingpumpkin** [comment]
Done
