### ISSUE TITLE
Authentication?

### ISSUE THREAD

**Issue by adambossy** [flashingpumpkin/django-socialregistration#4]
FlashingPumpkin, does socialregistration handle generation authentication? If so, can you post an example of how to handle account access in the views? For instance, I am assuming that since Facebook is based on PyFacebook, that I have access to request.facebook and the facebook.require_login() decorator.

Thanks,
Adam

**Comment by flashingpumpkin** [comment]
Yes, you do have access to request.facebook. If you look at the facebook_login source at http://github.com/flashingpumpkin/django-socialregistration/blob/master/socialregistration/views.py you'll see it's usage. 

I'm not sure what you mean with "generation authentication" though. If you mean the login decorators, these work too. To be honest though, I don't use facebook.require_login but only django.contrib.auth.login_required.

**Comment by adambossy** [comment]
Thanks, again! I'm not sure what I meant, either. :-P I think "generation" should have been "general." 

A quick example for how to use socialregistration for authentication would be a BIG help. I'm not clear what should replace this (from the PyFacebook docs):

```
def view(request):
    if not request.facebook.check_session(request):
        return render_to_response('view.fbml', {})
    else:
        return render_to_response('view.fbml', {'user': request.facebook.uid})
```

Looking through the socialregistration code, I see calls to check_session, use of uid, etc, but I'm not immediately sure what the control flow is. I assume there's a general way of handling the views logic using socialregistration_profile and _user that captures not only fb connect, but oauth and openid as well.

**Comment by flashingpumpkin** [comment]
```
from django.contrib.sites.models import Site
from django.contrib.auth.decorators import login_required
from socialregistration.models import FacebookProfile

@login_required
def view(request):
    profile = FacebookProfile.objects.get(user = request.user, site = Site.objects.get_current())
    return render_to_response('view.fbml', {'user': profile})
```

If you only use the Facebook auth backend, the @login_required decorator will make sure your users log in with Facebook Connect.

**Comment by flashingpumpkin** [comment]
closed
