### ISSUE TITLE
openID issue

### ISSUE THREAD

**Issue by EugeneLiang** [flashingpumpkin/django-socialregistration#40]
Hi, 
I have successfully implement facebook login using django-socialregistration.

However I am having problems with OpenID.

I tried loggin in with my openID profile ( google profile ) , and I get redirected to 
a url that does not belong to me.

What happens is that I will be requested to log in to Example.com, 
when my domain is www.tabwish.com.

How do i fix this?

Thank you for your help!

**Comment by flashingpumpkin** [comment]
You've got to set your correct domain in django's admin.

**Comment by EugeneLiang** [comment]
ok got it. thank you!

**Comment by EugeneLiang** [comment]
closed.
