### ISSUE TITLE
Invalid next parameter when using Facebook Connect

### ISSUE THREAD

**Issue by bjourne** [flashingpumpkin/django-socialregistration#42]
When authenticating using Facebook Connect, I get the following error:

API Error Code: 100
API Error Description: Invalid parameter
Error Message: next is not owned by the application.

It appears that the next parameter is not setup correctly by django-socialregistration.

**Comment by vvarp** [comment]
This error might appear when domain for your test page doesn't match domain provided in facebook app settings - please check if they are matching

**Comment by adeleinr** [comment]
Yep, I was having the same issue because I was using localhost:8084, changed it to just localhost and it works now. Thanks
