### ISSUE TITLE
FAIL: test_open_id_error (socialregistration.tests.templatetags.SocialRegistrationTemplateTagTests)

### ISSUE THREAD

**Issue by mixman** [flashingpumpkin/django-socialregistration#43]
This came up after upgrading packages (also pyfacebook to python-sdk), do latest openid libs work differently?

Django==1.2.3
oauth==1.0a
oauth2==1.2.0
python-openid==2.2.5
Python 2.6.4

Fix: self.assertEqual(result, u'False|')

<pre>
FAIL: test_open_id_error (socialregistration.tests.templatetags.SocialRegistrationTemplateTagTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/socialregistration/tests/templatetags.py", line 42, in test_open_id_error
    self.assertEqual(result, u'|')
AssertionError: u'False|' != u'|'
</pre>

**Comment by cpauya** [comment]
Quick fix is to edit the above test file and change the following at line 42:

```
    self.assertEqual(result, u'|')
```

to

```
    self.assertEqual(result, u'False|')
```
