### ISSUE TITLE
TemplateSyntaxError at / Caught NoReverseMatch while rendering: Reverse for 'facebook_login' with arguments '()' and keyword arguments '{}' not found.

### ISSUE THREAD

**Issue by ghost** [flashingpumpkin/django-socialregistration#48]
Caught NoReverseMatch while rendering: Reverse for 'facebook_login' with arguments '()' and keyword arguments '{}' not found.

In template /usr/local/lib/python2.6/dist-packages/socialregistration/templates/socialregistration/facebook_button.html, error at line 6

My first assumption was that I was not including socialregistration's URLs correctly but I have this in my urls.py file

from socialregistration.urls import *

Any ideas?

**Comment by flashingpumpkin** [comment]
Did you add the facebook API settings to your settings.py file?

**Comment by ghost** [comment]
Yes I did. I ended up getting it to work by just copying and pasting pretty much everything in SR's urls.py directly into my urls.py. Is that correct?

**Comment by davidmarble** [comment]
No, you add     

```
url(r'^social/', include('socialregistration.urls')),
```

to your urlpatterns
