### ISSUE TITLE
Best way to show logged in username with FB

### ISSUE THREAD

**Issue by rays** [flashingpumpkin/django-socialregistration#49]
I'm purely using facebook SSO for a project for general user interaction. Whats the best way to show the logged in username and profile picture of the logged in user. I should note I'm using SOCIALREGISTRATION_GENERATE_USERNAME

**Comment by ghost** [comment]
I'm not really sure. Using facebook's python sdk you can do something like this in your views:
    graph = request.facebook.graph 
    profile = graph.get_object("me")

I'm wondering if there is a better way to do it though. Sometimes I have issues when the user is no longer authenticated with facebook but their session no my site is still valid. Maybe someone could add their two cents.
