### ISSUE TITLE
Weirdness with blank request.facebook object

### ISSUE THREAD

**Issue by statico** [flashingpumpkin/django-socialregistration#5]
I have the `socialregistration.context_processors.auth` context processor installed, and the `{{ get_avatar }}` context variable works well -- I can see my Facebook profile icon.

However, when I try to access `{{ request.facebook }}`, its attributes are useless. `request.facebook` is undoubtedly a `djangofb.Facebook`, but its useful attributes are blank. `request.facebook.api_key` is populated but things like `request.facebook.uid` are `None`.

Any ideas what could be causing this?

**Comment by flashingpumpkin** [comment]
Hey there.

I just removed the context_processors.py file as there was too much "magic" going on about figuring out where the user came from to fetch avatars etc. Nothing that a registration application should do, really, but rather the application / coder using django-socialregistration. 

However, when using FacebookConnect I'd recommend using the native JavaScript API over pyfacebook.

**Comment by flashingpumpkin** [comment]
`request.facebook.uid` is now enabled if you add `socialregistration.middleware.FacebookMiddleware` to your settings.

It's basically just a wrapper to call `request.facebook.check_session(request)` on each request instead of explicitly in your views.

**Comment by statico** [comment]
Awesome.

The real problem was that I was using `get_avatar` instead of the JavaScript, but the call to `get_avatar` was failing because I wasn't passing `{% url socialregistration.views.logout %}` as the parameter to `FB.Connect.logoutAndRedirect`, the session key wasn't being cleared, and the `FacebookError` from an invalid session key was bubbling up.

Solution: `<a href="#" onclick="FB.Connect.logoutAndRedirect('{% url socialregistration.views.social_logout %}'); return false">Log out of Facebook</a>`

**Comment by statico** [comment]
(closing, thanks!)
