### ISSUE TITLE
setup.py fails at fetching httplib2

### ISSUE THREAD

**Issue by maraujop** [flashingpumpkin/django-socialregistration#50]
Hi there,

I'm setting `django-socialregistration` for the first time. I have run:

<pre>python setup.py install</pre>

When getting to:

<pre>
Using /usr/local/lib/python2.6/dist-packages
Searching for httplib2==0.4.0
Reading http://pypi.python.org/simple/httplib2/
Reading http://code.google.com/p/httplib2/
Reading http://bitworking.org/projects/httplib2/
Best match: httplib2 0.4.0
Downloading http://bitworking.org/projects/httplib2/dist/httplib2-0.4.0.tar.gz
error: Can't download http://bitworking.org/projects/httplib2/dist/httplib2-0.4.0.tar.gz: 404 Not Found
</pre>

Looks like easy_install URL is broken. So I guess somewhere in the documentation you could warn the user to install this dependency manually from http://httplib2.googlecode.com/files/httplib2-0.4.0.tar.gz
or use a Linux package system such as apt.

Thanks, regards
Miguel Araujo

**Comment by maraujop** [comment]
You could also mention in your documentation to run `syncbd` after setup

**Comment by flashingpumpkin** [comment]
Just tested, and httplib2 is downloading fine. It's not a direct dependencie of socialreg though, but of oauth or openid. Anyway, added the syncdb tip to the readme.
