### ISSUE TITLE
oauth_callback not recognized by Twitter

### ISSUE THREAD

**Issue by zerok** [flashingpumpkin/django-socialregistration#52]
It seems like the oauth_callback parameter is set to late for Twitter to actually use it. From what I could gather so far it should be set when requesting the original request token and not just when accessing the authentication URL.

Following this, the oauth_callback also doesn't do anything with the oauth_verifier included in the callback and therefor can't create a valid access token.

I've written a quick-fix for this available on https://gist.github.com/94cb6ca69e0e05aa81c5 but I'm not really sure how to integrate the oauth_verifier parameter. Accessing it directly from within _get_access_token doesn't feel right :-/

**Comment by flashingpumpkin** [comment]
Hm. The sites we're running socialreg with twitter seem to work just fine.

**Comment by flashingpumpkin** [comment]
Yes you are right. 

The [RFC](http://tools.ietf.org/html/rfc5849) describes the first request to include the callback.

**Comment by zerok** [comment]
Added a pull-request. Sorry for creating another ticket :-( I didn't really expect the request to opening yet another issue :-(
