### ISSUE TITLE
OAuth callback URL = sign needs to be URL quoted

### ISSUE THREAD

**Issue by altendky** [flashingpumpkin/django-socialregistration#56]
Disclaimer: first issue on github so please forgive all my impending faux pas

User/Project@SHA: ref flashingpumpkin/django-socialregistration@c9b82ff87ac79c4afdc66cfc9e4686111159756d

I have two issues, one before the above commit and another after.

Before the commit:
Twitter authentication attempts go through to the Twitter site and allow me to allow my application.  The issue is that it then continues onto a Twitter page showing a PIN that I am supposed to enter on my site...  where?  I have no idea.  I haven't figured out any resolution to this.

After the commit:
I get an OAuthError exception saying "Invalid response while obtaining request token from "api.twitter.com"."  Digging deeper I found that Twitter seems to be returning a 401 saying "Failed to validate oauth signature and token".  After much ado I found:

http://dev.twitter.com/pages/auth#request-token

and noticed that not only did they url encode the callback url parameter but they also encoded the = before it to %3D (see the first gray text box).  Doing the same 'manually' reverted me back to the pre-commit functionality.  Alternatively see:

https://gist.github.com/764265

for a simple patch that does the same using urllib.quote().  Note that even then I still get the Twitter PIN page rather than being returned to my site even after applying my patch to the latest commit.

I assume this commit didn't break everything for everyone else but I don't know why I'm special at this point.  Might be that I'm integrating this into django-nonrel for use on Google AppEngine but I don't know how.  Locally I'm running Python 2.6 while GAE is Python 2.5.

**Comment by flashingpumpkin** [comment]
> Before the commit:
> Twitter authentication attempts go through to the Twitter site and allow me to allow my application. The issue is that it then continues onto a Twitter page showing a PIN that I am supposed to enter on my site... where? I have no idea. I haven't figured out any resolution to this.

This should not happen if you configure twitter to use a callback url. It's in your application settings in your twitter profile.

**Comment by altendky** [comment]
Thank you, it is now working (if I maintain my patch).  There are various stupid reasons I did not set that...  :[  though perhaps it should be in the readme?  After more exploration yesterday my 'patch' seems to simply cause the oauth_callback variable to be thrown out.  Still, isn't the application supposed to be able to override the URL set on Twitter?  Isn't that what this code is supposed to do?

User/Project@SHA: ref flashingpumpkin/django-socialregistration@c9b82ff87ac79c4afdc66cfc9e4686111159756d

This would be helpful in my case to make it usable on both my localhost (as 127.0.0.1 at least) and on GAE without having to change the setting in my Twitter account.  Although I guess I'm still stuck with the latest dev version not working as-is.

Thanks again for setting me straight on the callback setting on Twitter.

**Comment by flashingpumpkin** [comment]
Yes. That code should do exactly this. I've just tested it out now, and it works. Not sure what was going wrong on your side.

**Comment by 0101** [comment]
I had exactly the same issue as altendky with the oauth_callback. The documentation [1] says you should use POST for getting the token, so I changed [2] the method to POST and it seems to be working as expected.

[1] http://dev.twitter.com/pages/auth#request-token
[2] https://github.com/0101/django-socialregistration/commit/2a3ca897f115ddbfd8900c93ecc05fdefa92b37a

**Comment by flashingpumpkin** [comment]
Pulled in the change, thanks!
