### ISSUE TITLE
How to install requirements package

### ISSUE THREAD

**Issue by thelinh** [flashingpumpkin/django-socialregistration#58]
Hi every body,
I'm a django newbie. Please help me install requirements package such as : 

```
  oauth2
  python-openid
  python-sdk
```

I have already downloaded some packages:

```
    dgouldin-python-oauth2-1.1.3-4-g21b4116 --> oauth2
    facebook-python-sdk-322930c
    openid-python-openid-2.2.5-0-gb666238
    flashingpumpkin-django-socialregistration-v0.4-tag-0-g98e0cb5
```

then i executed the command "sudo python setup.py install" in the child directory of those packages which contains file setup.py.

But after runing this tutorial, I get this message error:

```
  'module' object has no attribute 'get_user_from_cookie'

  the exception value is: 'module' object has no attribute 'get_user_from_cookie'
```

I think because i have install  those requirements package in a wrong ways. so the error occour in file : socialregistration/middleware.py line 23:
          fb_user = facebook.get_user_from_cookie(request.COOKIES, 

So, please help me. 

Thanks

**Comment by flashingpumpkin** [comment]
I suggest you install things like pip and virtualenv:

```
sudo apt-get install python-setuptools
sudo easy_install virtualenv pip
virtualenv yourproject
cd yourproject
source bin/activate
pip install django-socialregistration
# go to the folder
pip install -r requirements.txt
```

**Comment by sebfie** [comment]
How did you solve this problem?
