### ISSUE TITLE
Something wrong with facebook integration

### ISSUE THREAD

**Issue by ghost** [flashingpumpkin/django-socialregistration#59]
I followed readme, got all the dependency installed. It appears that facebook's JS, all.js, 
line 9, is causing this error on all browsers. Is this an fb issues with the javascript sdk or something to do with socialregistration? 

 Error occurs on: FB.provide('JSON',{stringify:function(a){if(window.Prototype&&Object.toJSON){return Object.toJSON(a);}else return JSON.stringify(a);},parse:function(a){return JSON.parse(a);},flatten:function(c){var a={};for(var b in c)if(c.hasOwnProperty(b)){var d=c[b];if(null===d||undefined===d){continue;}else if(typeof d=='string'){a[b]=d;}else a[b]=FB.JSON.stringify(d);}return a;}});

**Comment by ghost** [comment]
Upon closer inspection on chrome the debug message is FB.login() called before calling FB.init().

I placed     {% facebook_js %} in my head and the body with the facebook login button. 
I even manually tried doing FB.init( {apiKey .. }) immediately after {% facebook_js %} but still to no avail. Help pls

**Comment by flashingpumpkin** [comment]
You've gotta place the `{% facebook_button %}` before the `{% facebook_js %}`

It's got to do with the old connect api that socialregistration still uses. It required the JavaScript to be in the body iirc.
