### ISSUE TITLE
ValueError with Twitter redirect

### ISSUE THREAD

**Issue by jorilallo** [flashingpumpkin/django-socialregistration#60]
Not sure what's going on with my installation when setting up Twitter authentication but I'm getting a ValueError:

ValueError at /social/twitter/redirect/
Exception Value:  
Unsupported URL ('https://api.twitter.com/oauth/request_token',)?oauth_callback=http%3A%2F%2F127.0.0.1%3A8000%2Fsocial%2Ftwitter%2Fcallback%2F ().
Exception Location: /Users/jorde/projects/app/env/lib/python2.6/site-packages/oauth2/**init**.py in url, line 289

Any ideas?

**Comment by flashingpumpkin** [comment]
You are passing in a tuple as url when it should be a string.
