### ISSUE TITLE
Difficulty in setting up with python 2.5 for use with GAE via django nonrel

### ISSUE THREAD

**Issue by Folcon** [flashingpumpkin/django-socialregistration#63]
So I'm dumping the error message below:

'facebook_tags' is not a valid tag library: ImportError raised loading socialregistration.templatetags.facebook_tags: cannot import name parse_qs
Request Method: GET
Request URL:    http://localhost:8000/solve/
Django Version: 1.3 alpha 1
Exception Type: TemplateSyntaxError
Exception Value:  
'facebook_tags' is not a valid tag library: ImportError raised loading socialregistration.templatetags.facebook_tags: cannot import name parse_qs
Exception Location: F:\Coursework\Code\GAE\django-guestbook\django\template\defaulttags.py in load, line 957
Python Executable:  C:\Python25\python.exe
Python Version: 2.5.0
Python Path:    ['F:\Coursework\Code\GAE\django-guestbook', 'F:\Coursework\Code\GAE\django-guestbook\djangoappengine\lib', 'F:\Coursework\Code\GAE\django-guestbook\..\django-guestbook\djangoappengine\lib', 'C:\Program Files (x86)\Google\google_appengine', 'C:\Program Files (x86)\Google\google_appengine\lib\antlr3', 'C:\Program Files (x86)\Google\google_appengine\lib\fancy_urllib', 'C:\Program Files (x86)\Google\google_appengine\lib\ipaddr', 'C:\Program Files (x86)\Google\google_appengine\lib\webob', 'C:\Program Files (x86)\Google\google_appengine\lib\yaml\lib', 'C:\Python25\lib\site-packages\html5lib-0.95_dev-py2.5.egg', 'C:\Python25\lib\site-packages\djangoappengine-1.0-py2.5.egg', 'C:\Python25\lib\site-packages\django_dbindexer-0.2-py2.5.egg', 'C:\Python25\lib\site-packages\djangotoolbox-0.9.1-py2.5.egg', 'C:\Python25\lib\site-packages\django_socialregistration-0.4.3-py2.5.egg', 'C:\Python25\lib\site-packages\python_openid-2.2.5-py2.5.egg', 'C:\Python25\lib\site-packages\oauth2-1.5.150-py2.5.egg', 'C:\Python25\lib\site-packages\httplib2-0.6.0-py2.5.egg', 'C:\Python25\python25.zip', 'C:\Python25\DLLs', 'C:\Python25\lib', 'C:\Python25\lib\plat-win', 'C:\Python25\lib\lib-tk', 'C:\Python25', 'C:\Python25\lib\site-packages', 'C:\Python25\lib\site-packages\PIL']

I followed the instructions laid out in the readme. If I swap to python 2.5 and import httplib2 it works however I can't work out at the minute why it's not working in 2.5.

**Comment by flashingpumpkin** [comment]
Any luck on this? There's no Python 2.5 or GAE within my reach

**Comment by jaylett** [comment]
From http://docs.python.org/library/urlparse.html I note that `parse_qs` was introduced in 2.6, and was previously available in the `cgi` module (where it's currently retained for bc, but deprecated).

**Comment by flashingpumpkin** [comment]
I assume this is fixed by eef4ba37 then.
