### ISSUE TITLE
Error: dictionary update sequence element #0 has length 1; 2 is required

### ISSUE THREAD

**Issue by astanway** [flashingpumpkin/django-socialregistration#67]
I get this error whenever I try to access any socialregistration url at www.../social/{facebook/login/, etc}.

**Comment by flashingpumpkin** [comment]
Can you post the traceback please?

**Comment by astanway** [comment]
Environment:

Request Method: POST
Request URL: http://sm.rutgers.edu/citizenscience/social/facebook/login/
Django Version: 1.2.4
Python Version: 2.5.4
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'socialregistration',
 'citsci']
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfResponseMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'socialregistration.middleware.FacebookMiddleware')

Traceback:
File "/usr/local/lib/python2.5/site-packages/django/core/handlers/base.py" in get_response
1.                         request.path_info)
   File "/usr/local/lib/python2.5/site-packages/django/core/urlresolvers.py" in resolve
2.                     sub_match = pattern.resolve(new_path)
   File "/usr/local/lib/python2.5/site-packages/django/core/urlresolvers.py" in resolve
3.                         sub_match_dict.update(self.default_kwargs)

Exception Type: ValueError at /social/facebook/login/
Exception Value: dictionary update sequence element #0 has length 1; 2 is required

**Comment by flashingpumpkin** [comment]
I guess something is wrong how you set up the urls. Could you post your urls.py file too please?

`self.default_kwargs` does not appear to be a dictionary:

```
>>> d = dict()
>>> d.update('foo')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ValueError: dictionary update sequence element #0 has length 1; 2 is required
>>> d.update({ 'foo': 1 })
>>> d
{'foo': 1}
```

**Comment by astanway** [comment]
from django.conf.urls.defaults import *
from django.conf import settings
from citsci.forms import FieldFormset
from citsci.forms import EmptyFieldFormset
import socialregistration.urls

urlpatterns = patterns('citsci.views',

```
url(r'^social/', include('socialregistration.urls'), 'social_login'),
(r'^$', 'social_login'),
(r'^social_login$', 'social_login'),
(r'^logout_view$', 'logout_view'),
(r'^index$', 'index'),
(r'^your_projects$', 'your_projects'),
(r'^browse$', 'browse'),
url(r'^create_project2$', 'create_project2', {'formset_class': FieldFormset, 'template': 'citsci/create_project2.html'}, name='example_table'),
(r'^create_project1$', 'create_project1'),
(r'^invite$', 'invite'),
(r'^(?P<pid>\d+)$', 'project_page'),
(r'^(?P<pid>\d+)/confirm$', 'project_page', {'publish': 'True'}),
(r'^(?P<pid>\d+)/submit$', 'submit'),
(r'^edit/(?P<pid>\d+)$', 'edit'),
url(r'^edit2/(?P<pid>\d+)$', 'edit2', {'formset_class': EmptyFieldFormset}),
(r'^(?P<pid>\d+)/join$', 'join'),
(r'^(?P<pid>\d+)/leave$', 'leave'),
(r'^(?P<pid>\d+)/delete$', 'delete'),
(r'^(?P<pid>\d+)/deleted$', 'delete_confirm'),
```

)

**Comment by flashingpumpkin** [comment]
You don't need to import `socialregistration.urls`.

Also, you're passing in `social_login` after doing the `include('socialregistration.urls')`, which is expected to be a `dict`:

http://docs.djangoproject.com/en/1.3/topics/http/urls/#url

This should fix it:

```
from django.conf.urls.defaults import *
from django.conf import settings
from citsci.forms import FieldFormset
from citsci.forms import EmptyFieldFormset


urlpatterns = patterns('citsci.views',
    url(r'^social/', include('socialregistration.urls')),
    (r'^$', 'social_login'),
    ...
)
```

**Comment by astanway** [comment]
yeah, it was the social_login argument. I figured I needed to pass your logic to one of my templates; I didn't realize you had your own. Thanks for the help.
