### ISSUE TITLE
Account Connect?

### ISSUE THREAD

**Issue by girasquid** [flashingpumpkin/django-socialregistration#7]
Maybe I'm just missing something, but I'm stuck here - is there a way to 'connect' accounts on other sites to an already-existing user?

For example, I've already signed up on Really Awesome Website, so I don't need to sign up again - but I'd like to connect my Facebook and Twitter accounts so that I can sign in with those as well.

Is there a way to do this already? If there isn't...how would I do it?

**Comment by flashingpumpkin** [comment]
Yes there is. Just use the same template tags for Facebook Connect as you would for registration. Depending on if the user is already logged in or not it will create just the `FacebookProfile` object and link it to the existing user - or create both, the `User` object and the `FacebookProfile` object.

**Comment by flashingpumpkin** [comment]
Have a look here:
http://github.com/flashingpumpkin/django-socialregistration/blob/master/socialregistration/templates/socialregistration/facebook_button.html
and
http://github.com/flashingpumpkin/django-socialregistration/blob/master/socialregistration/templatetags/facebook_tags.py

**Comment by girasquid** [comment]
Oh, awesome - thanks for the tip.

**Comment by girasquid** [comment]
Sorry, one more question - does it work this way for Twitter accounts? I'm logged in as a regular contrib.auth user(originally created via socialregistration's Twitter auth), and I've deleted the TwitterProfile object associated with the user. When I click on 'sign in with Twitter' to connect the Twitter account, I'm sent back to the setup page, instead of just having the association made. Does this work for Twitter too?

**Comment by mvh** [comment]
Hey, I have the same question - the Facebook stuff seems to work just like I want, but the Twitter stuff only seems to work for a new account.  Is this intentional, unfinished, or just different?

Thanks for your work on the code...

**Comment by girasquid** [comment]
I had that problem too - if you take a look at my fork of socialregistration, I updated it so that connecting a Twitter account works as well, although you may have to dig through the code a bit. Message me if you get stuck.
