### ISSUE TITLE
Fix Logout Tag in Docs ({% url auth_logout %})

### ISSUE THREAD

**Issue by dbrgn** [flashingpumpkin/django-socialregistration#70]
After some playing around I found out that you need to change the `{% url auth_logout %}` tag in your README to `{% url social_logout %}`.

**Comment by flashingpumpkin** [comment]
`{% url social_logout %}` is just a wrapper around the built in `{% url auth_logout %}`, but I'll change

**Comment by dbrgn** [comment]
`auth_logout` did not work for me, `social_logout` did. Whatever the problem was, thanks for the change.
