### ISSUE TITLE
Can't pickle <type 'cStringIO.StringI'>: attribute lookup cStringIO.StringI failed

### ISSUE THREAD

**Issue by dbrgn** [flashingpumpkin/django-socialregistration#72]
PicklingError at /social/setup/
Can't pickle <type 'cStringIO.StringI'>: attribute lookup cStringIO.StringI failed

This did not happen with yesterday's code basis, was probably introduced by one of the recent commits.

It occurs at a clean install after authenticating at Twitter and creating an account (just after clicking the button at /social/setup).

Traceback:

<pre>Environment:

Request Method: POST
Request URL: http://feedr.io/social/setup/

Django Version: 1.3
Python Version: 2.7.1
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'socialregistration',
 'front',
 'debug_toolbar',
 'django_extensions']
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'socialregistration.middleware.FacebookMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware')

Traceback:
File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                         response = callback(request, *callback_args, **callback_kwargs)
File "/usr/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
  93.                     response = view_func(request, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/django_socialregistration-0.4.4-py2.7.egg/socialregistration/views.py" in setup
  101.     _login(request, user, social_profile, social_client)
File "/usr/lib/python2.7/site-packages/django_socialregistration-0.4.4-py2.7.egg/socialregistration/views.py" in _login
  47.     login(request, user)
File "/usr/lib/python2.7/site-packages/django/contrib/auth/__init__.py" in login
  80.         request.session.cycle_key()
File "/usr/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py" in cycle_key
  271.         self.create()
File "/usr/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py" in create
  40.                 self.save(must_create=True)
File "/usr/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py" in save
  57.             session_data = self.encode(self._get_session(no_load=must_create)),
File "/usr/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py" in encode
  93.         pickled = pickle.dumps(session_dict, pickle.HIGHEST_PROTOCOL)

Exception Type: PicklingError at /social/setup/
Exception Value: Can't pickle <type 'cStringIO.StringI'>: attribute lookup cStringIO.StringI failed</pre>

**Comment by flashingpumpkin** [comment]
You might have gotten a faulty commit. The recent HEAD should work fine, I'll try

**Comment by dbrgn** [comment]
I tried with 43e423f15ed78c63a77a92fa1f1b5551ff5c4cce

**Comment by flashingpumpkin** [comment]
Aight. Didn't realize that logging in actually writes the session to the storage. It still was holding the client which had the request attached...

Commit above fixes it. Just tested it out with a clean install with facebook, twitter and openid

**Comment by dbrgn** [comment]
Thank you :)
