### ISSUE TITLE
What is the use of OpenID stores?

### ISSUE THREAD

**Issue by vallettea** [flashingpumpkin/django-socialregistration#77]
Hello, i would like to delete some of these but i'm scared to destroy some accounts...
what is the use of those and can they be deleted?
thanks

**Comment by flashingpumpkin** [comment]
Have a look here: 

https://github.com/openid/python-openid/blob/master/openid/store/interface.py

**Comment by flashingpumpkin** [comment]
Notably, all the `cleanupFOO` methods are missing from socialreg. Best is to actually write those, and you'd be able to delete expired ones with `socialregistration.utils.OpenIDStore.cleanup`

**Comment by vallettea** [comment]
ok thanks
