### ISSUE TITLE
facebook_button template function doesn't accept arguments

### ISSUE THREAD

**Issue by joshavant** [flashingpumpkin/django-socialregistration#87]
The documentation states:

> You can also specify your own custom button image by appending it to the facebook_button template tag:
> 
>    `{% facebook_button 'http://example.com/other_facebook_button.png' %}`

However, adding the following line to a template (with a real image source, of course):

`{% facebook_button 'http://example.com/other_facebook_button.png' %}`

Throws an exception that `facebook_button takes 0 arguments`.

Workaround for now is modifying the templates/socialregistration/facebook_button.html manually.

**Comment by flashingpumpkin** [comment]
See issue #88
