### ISSUE TITLE
Setting FACEBOOK_REQUEST_PERMISSIONS doesn't actually change requested permissions

### ISSUE THREAD

**Issue by joshavant** [flashingpumpkin/django-socialregistration#88]
The documentation states:

> Add FACEBOOK_REQUEST_PERMISSIONS to your settings. This is a comma seperated list of the permissions you need. e.g:
> 
> `FACEBOOK_REQUEST_PERMISSIONS = 'email,user_about_me'`

However, adding the following line to settings.py:

`FACEBOOK_REQUEST_PERMISSIONS = 'user_location,user_photos,publish_stream'`

Wouldn't actually change the permissions requested by socialregistration.

Workaround for now is modifying the templates/socialregistration/facebook_js.html manually.

**Comment by flashingpumpkin** [comment]
You might not be using the master branch from here. PyPI is still on v0.4.3 - I'm a bit reluctant to push the code to PyPI while there is still outstanding issues.

**Comment by flashingpumpkin** [comment]
It's online now
