### ISSUE TITLE
Error 'module' object has no attribute 'get_user_from_cookie'

### ISSUE THREAD

**Issue by sebfie** [flashingpumpkin/django-socialregistration#89]
Hello,

When i try to use your module, I got this error :

'module' object has no attribute 'get_user_from_cookie'

How can i fix this?

Thank you

**Comment by flashingpumpkin** [comment]
Could you post the whole traceback?

**Comment by sebfie** [comment]
Hello, 

I solved my problem running this :
pip install -e git+https://github.com/facebook/python-sdk.git#egg=FacebookSDK

TemplateSyntaxError at /
But now i have an other problem :
'facebook_tags' is not a valid tag library: ImportError raised loading socialregistration.templatetags.facebook_tags: No module named oauth2

I have this problem when i run app with apache

**Comment by flashingpumpkin** [comment]
Did you install python-oauth2?

**Comment by mocha** [comment]
Oddly enough, I had the problem in the opposite order - I installed oauth2 and the template tag error went away, but i'm still having trouble with 'get_user_from_cookie'

The traceback is as follows:

Environment:

Request Method: GET
Request URL: http://austin.pb-prod1.com:8000/

Django Version: 1.3
Python Version: 2.6.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.humanize',
 'pb.pb_app',
 'socialregistration',
 'easy_thumbnails',
 'pagination',
 'ajax_select']
Installed Middleware:
('pb_app.middleware.SubdomainMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'pagination.middleware.PaginationMiddleware',
 'socialregistration.middleware.FacebookMiddleware')

Traceback:
File "/usr/local/lib/python2.6/dist-packages/django/core/handlers/base.py" in get_response
1.                     response = middleware_method(request)
   File "/usr/local/lib/python2.6/dist-packages/socialregistration/middleware.py" in process_request
2.         fb_user = facebook.get_user_from_cookie(request.COOKIES,

Exception Type: AttributeError at /
Exception Value: 'module' object has no attribute 'get_user_from_cookie'

**Comment by sebfie** [comment]
Hello,

My big mistake was to use the binary python of my system instead of my web's server. So, when i want to install a module, i have to use "/Applications/MAMP/python/bin/python" and not "python".
