### ISSUE TITLE
Open ID form submits 'example.com' as referring domain

### ISSUE THREAD

**Issue by adambossy** [flashingpumpkin/django-socialregistration#9]
To reproduce:
1. Create a page with the {% openid_form %} tag.
2. Use "yahoo.com" or "https://www.google.com/accounts/o8/id" in the form.
3. Submit the form.
4. You're redirected to the respective domain (yahoo or google in this case), but it uses 'example.com' as the referring domain instead of my own site. When you log in to the open id provider you're redirected back to example.com, which doesn't exist.

**Comment by girasquid** [comment]
It sounds like this issue is cropping up because you haven't configured the default contrib.Site for your app - have you done that yet? When you first fire up a Django app contrib.sites will put in a default site for example.com with ID 1.

**Comment by flashingpumpkin** [comment]
I second the above reply. You've gotta configure django.contrib.sites to point to your domain and not to example.com

**Comment by adambossy** [comment]
Doh! I cleared my database and forgot to change the Site. I figured this was a default value with that open id providers used. Thanks for the quick response!
