### ISSUE TITLE
user not defined exception

### ISSUE THREAD

**Issue by Sashan** [flashingpumpkin/django-socialregistration#91]
I've hit a small problem when playing with OpenID auth. Anytiem I tried to sign-in user, who
was already signed in I've received exception:
     user not defined

patch bellow solves my prolem:
diff --git a/socialregistration/views.py b/socialregistration/views.py
index 1788fef..f050dc2 100644
--- a/socialregistration/views.py
+++ b/socialregistration/views.py
@@ -305,7 +305,7 @@ def openid_callback(request, template='socialregistration/openid.html',
             except OpenIDProfile.DoesNotExist: # There can only be one profile with the same identity
                 profile = OpenIDProfile.objects.create(user=request.user,
                     identity=identity)
-                _connect(user, profile, client)
- ```
             _connect(request.user, profile, client)
  
       return HttpResponseRedirect(_get_next(request))
  ```

**Comment by flashingpumpkin** [comment]
That's fixed in 28239c1361eb1155576f
