### ISSUE TITLE
Default twitter button image goes to 404 page

### ISSUE THREAD

**Issue by albertsun** [flashingpumpkin/django-socialregistration#93]
Twitter must have changed their urls?

The default Twitter button image goes to http://apiwiki.twitter.com/f/1242697608/Sign-in-with-Twitter-lighter.png which is a 404 page

Seems like the new link should go to https://si0.twimg.com/images/dev/buttons/sign-in-with-twitter-l.png

**Comment by flashingpumpkin** [comment]
That's fixed in b2b3aba61820008011dd
