### ISSUE TITLE
UnboundLocalError: local variable 'user' referenced before assignment

### ISSUE THREAD

**Issue by jaylett** [flashingpumpkin/django-socialregistration#95]
socialregistration/views.py:39 is:

```
                _connect(user, profile, client) 
```

but should probably be:

```
                _connect(request.user, profile, client) 
```

which actually exists in scope at that point.

**Comment by flashingpumpkin** [comment]
Yes, indeed. Pulling that in now, it's not the first of its kind.

I'm currently a bit uneasy about socialreg as there's no tests at all for all the different apis which turns the whole thing into a try and error exercise. You might not have a good suggestion about how to sanely test everything?

OpenID seems the easiest - it would only be a question of starting up an openid provider from python. But how would one go about testing integration with twitter's and facebook's apis? Creating a mock server for both seems like a lot of overhead. I'm not quite sure how to do it, but would like to get socialreg rock solid which obv can only happen with a good test suit.

Anyway, a bit in a hurry right now...

**Comment by flashingpumpkin** [comment]
Pulled in but leaving the issue open

**Comment by jaylett** [comment]
I've been thinking about automated testing of our social auth integrations for months, and haven't come up with a good solution. OpenID and even true OAuth 2 (such as Twitter) sounds largely practical as you say, but Facebook you'd need to create a bunch of Javascript to emulate the whole FB.init / FB.login. At least from October you could do that just over OAuth 2, which would probably simplify things considerably.
